default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: timer_development

test:
  <<: *default
  database: timer_test

production:
  <<: *default
  database: timer_production
  username: timer
  password: <%= ENV['TIMER_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
